#!/bin/bash
# Writes /etc/nginx/cloudflare-realip.conf from Cloudflare's published IP ranges and
# limits ports 80/443 to Cloudflare in ufw. Safe to run repeatedly (weekly cron).
set -euo pipefail
v4=$(curl -fsS https://www.cloudflare.com/ips-v4)
v6=$(curl -fsS https://www.cloudflare.com/ips-v6)
[ -n "$v4" ] && [ -n "$v6" ] || { echo "Could not download Cloudflare ranges" >&2; exit 1; }

tmp=$(mktemp)
{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%F). Do not edit."
  for ip in $v4 $v6; do echo "set_real_ip_from $ip;"; done
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
install -m 644 "$tmp" /etc/nginx/cloudflare-realip.conf
rm -f "$tmp"

if command -v ufw >/dev/null; then
  # Drop old web rules, then allow 80/443 only from Cloudflare.
  while ufw status numbered | grep -qE "(80|443)/tcp.*ALLOW IN"; do
    n=$(ufw status numbered | grep -E "(80|443)/tcp.*ALLOW IN" | head -1 | sed -E 's/^\[ *([0-9]+)\].*/\1/')
    yes | ufw delete "$n" >/dev/null
  done
  for ip in $v4 $v6; do
    ufw allow proto tcp from "$ip" to any port 80,443 comment cloudflare >/dev/null
  done
fi

nginx -t && systemctl reload nginx
echo "Cloudflare ranges updated."
